### ISSUE TITLE
.p3d error spams our server logs

### ISSUE THREAD

**Issue by SanyaZ** [SachaOropeza/AH64D-Project#20] opened 2017-04-24 04:48 UTC
I was not given the server log but this error was pasted to me. It happens when ever the latest version of the apache is on the server. They wont use it till this log gets fixed. if you could fix it that would be great.
7:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 492, sum of weights is 200, should be 100
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 493, sum of weights is 200, should be 100 
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 494, sum of weights is 200, should be 100 
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 495, sum of weights is 200, should be 100 
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 496, sum of weights is 200, should be 100 
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 497, sum of weights is 200, should be 100 
167:29 Warning: fza_ah64_us\fza_ah64d_b2.p3d.5, vertex: 498, sum of weights is 200, should be 100

**Comment by SachaOropeza** [comment] 2017-04-24 05:36
This error concerns the main 3D file and it is directly linked to the addon builder software such as O2. It is pretty common in addons creation but it isn't a big deal as it doesn't impact performances.

**Comment by SanyaZ** [comment] 2017-04-24 05:38
Right.. They wont use it otherwise.. Im assuming it cant be fixed easily then?

**Comment by SachaOropeza** [comment] 2017-04-24 11:08
Franze cured those vertex warnings by opening and resaving the concerned file. Other than that, I'll check into that, but this is a low priority at this time.

**Comment by Foehammer47** [comment] 2017-04-26 22:10
Hello I am currently the one asking about this mod from the community SanyaZ is from. When we spawn in one of the helicopters the zeus operator is frozen for 30-45 seconds then afterwards he is unfrozen then everyone else in the server is frozen for 30-40 seconds. When we place the helicopter in the editor and then launch the server it takes the server over 4 minutes to launch and we have increased loading times. When the helicopter is spawn at any time the RPT is spammed with over 33,875 lines of Warnings (i.e. the ones above) and then the RPT goes from 2KB to over 3000 KB and yes that effects performance. I hope this message helps you try to figure out what the issue is and if there is a fix.

**Comment by blindbat2006** [comment] 2017-05-29 21:42
Hello have you tried building the 2 folders (fza_ah64_controls & fza_ah64_us)  in Arma Tools >> Addon Builder this has fixed the issues in the rpt for our community.

**Comment by Foehammer47** [comment] 2017-06-01 07:34
I will try this method. I know we have JSHOCK in our community and he is really good at scripting and figuring this stuff out. Thank you for the intel

**Comment by blindbat2006** [comment] 2018-04-05 05:34
Issue is with pbo creation. Use pbobuilder or another tool to create pbo.
@SachaOropeza can you close this issue.

**Comment by SachaOropeza** [comment] 2018-04-05 06:56
Closes.

**Closed** 2018-04-05 06:57 UTC

**Comment by Max255PL** [comment] 2018-05-06 02:11
If this is an issue with .pbo creation why does it still persists with the newest official version from Armaholic and/or Workshop? Or was this not yet adressed on your side?

PS. Please don't take this as a snarky comment, it's not intended as one, just a honest question.

**Comment by Foehammer47** [comment] 2018-05-06 02:16
Hello. I wrote this comment like over a year ago. After not receiving a reply we stopped using this in our mod pack. We would receive over 33 thousand lines of error for for the weapon systems and wrong weights. I havent tried the recently updated ones on workshop mainly because we switched to a Navy unit with a 160th SOAR so we mainly use the AH-6 and MH-6 variants. 
    On Saturday, May 5, 2018, 9:11:55 PM CDT, Max <notifications@github.com> wrote:  
 
 
If this is an issue with .pbo creation why does it still persists with the newest official version from Armaholic and/or Workshop? Or was this not yet adressed on your side?

PS. Please don't take this as a snarky comment, it's not intended as one, just a honest question.

**Comment by blindbat2006** [comment] 2018-05-06 14:24
@Max255PL post up the log file will take a look (side not do you use ace3?).
@Foehammer47  Is konyo still about in your community I have tried to get in touch but no joy would love to take his Chinook on and update we (4thib.co.uk) have our own chinook but looking to upgrade from the HC2/4 to the HC3 with a view to upgrade it to HC5 and beyond.

**Comment by Max255PL** [comment] 2018-05-08 14:27
Here's the log with Apache only, downloaded directly from Workshop, the official version ofc.
[Arma3_x64_2018-05-08_16-21-33.zip](https://github.com/SachaOropeza/AH64D-Project/files/1984296/Arma3_x64_2018-05-08_16-21-33.zip)

And yes, we do use ACE normally but I fail to see the connection.

**Comment by blindbat2006** [comment] 2018-05-08 18:11
@Max255PL Had a look the logs thanks Max, Yes by the looks the pbo is not being binarized right.

@SachaOropeza see above mikero tools will spit out alot of problems if you try to binarize with it ( I can fix most but will wait until any updates are done) Addonbuilder from arma3tools will binarize it but doesnt worry about problems with model or scripts.
